[build]
rustc-wrapper = "sccache"
target-dir = "target"  # Use a consistent target directory
# jobs = 0  # Use all available CPU cores

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = [
    "-C", "incremental=true"    # Enable incremental compilation
]

[env]
RUSTC_WRAPPER = "sccache"
