name: Benchmark

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      pages: write
      issues: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: benchmark-cache-${{ matrix.os }}
          cache-on-failure: true

      - name: Install RISC Zero toolchain
        run: |
          curl -L https://risczero.com/install | bash
          $HOME/.risc0/bin/rzup install

      - name: Setup test files
        run: bash ./setup.sh

      - name: Run benchmark
        run: bash ./run_release.sh

      # - name: Run benchmark
      #   run: cargo bench --bench '*' -- --verbose

      # - name: Combine criterion results
      #   run: bash ./combine_criterion.sh

      # - name: Run benchmark action
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     tool: 'cargo'
      #     output-file-path: combined_criterion.json
      #     gh-pages-branch: gh-pages
      #     benchmark-data-dir-path: dev/bench
      #     github-token: ${{ github.token }}
      #     auto-push: true
